#
server:
  port: 7200
#
logging:
  config: classpath:logback.xml
#
spring:
  profiles: dev
  application:
    name: study-springcloud-provider
  main:
    web-application-type: servlet

# 注册中心配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #Eureka Client向Eureka Server发送心跳时间间隔
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: @eureka.client.defaultZone@
    # CacheRefresh线程的调度频率
    registry-fetch-interval-seconds: 30