#
eureka:
  #实例配置
  instance:
    hostname: study-springcloud-provider
#    ip-address: 150.158.110.15
    ip-address: 111.229.94.31
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #（★）续约！！！
    #向 server 发送心跳间隔，默认30秒
    #向服务端发送一次心跳，证明自己依然“存活”
    lease-renewal-interval-in-seconds: 30
    #指示 server 在删除此实例之前收到最后一次心跳之后等待的时间，默认90秒
    #告诉服务端，如果我90s之内没有给你发心跳，就代表我“死”了，将我踢出掉
    lease-expiration-duration-in-seconds: 90
  #客户端配置
  client:
    service-url:
      defaultZone: @eureka.server.list@
    #（★）服务注册及发现！！！
    #是否启用 client，默认true
    enabled: true
    #是否应将 client 注册到 server，默认为true
    register-with-eureka: true
    #是否获取 server 上的注册信息，默认为true
    fetch-registry: false
    #从 server 获取注册表信息间隔，默认30秒
    registry-fetch-interval-seconds: 30
    #（★）心跳！！！
    #心跳执行器线程池大小，默认2
    heartbeat-executor-thread-pool-size: 1
    #心跳超时重试延迟时间的最大乘数值，默认10
    #leaseRenewalIntervalInSeconds * heartbeatExecutorExponentialBackOffBound
    heartbeat-executor-exponential-back-off-bound: 10

    #（）缓存
    #是否禁用增量获取
    disable-delta: true
    #缓存刷新执行器线程池大小
    cache-refresh-executor-thread-pool-size: 2
    #缓存刷新超时重试延迟时间的最大乘数值，默认10
    #registryFetchIntervalSeconds * cacheRefreshExecutorExponentialBackOffBound
    cache-refresh-executor-exponential-back-off-bound: 10
    #（）连接
    #连接 server 超时时间，默认5秒
    eureka-server-connect-timeout-seconds: 5
    #读取 server 超时时间，默认8秒
    eureka-server-read-timeout-seconds: 8
    #连接 server 后的空闲等待时间，默认30秒
    eureka-connection-idle-timeout-seconds: 30
    #总连接数，client 连接all server的总连接数，默认200
    eureka-server-total-connections: 200
    #每个主机的总连接数，client 连接 server的单机连接数量，默认50
    eureka-server-total-connections-per-host: 50
    #询问eureka服务url信息变化的频率，默认为300秒
    eureka-service-url-poll-interval-seconds: 300
    #间隔多长时间再次复制实例信息到server，默认为30秒
    eureka.client.instance-info-replication-interval-seconds: 30
