#
server:
  port: 8100
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-provider
  main:
    web-application-type: servlet

#注册中心配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://114.67.102.8:7010/eureka/