#
server:
  port: 8080
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name:
  main:
    web-application-type:
  #数据源
  datasource:
    name: druid_datasource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.4.23:3306/remixed
    username: remixeddb
    password: remixeddb123
    initial-size: 10
    min-idle: 10
    max-active: 10
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.20.4.23:3306/remixed
      username: remixeddb
      password: remixeddb123
      initial-size: 20
      min-idle: 20
      max-active: 20
  #Redis
  redis:
    host: 114.67.102.8
    port: 6379
    password: abc123
    timeout: 6000
    jedis:
      pool:
        max-active: 6000

# MyBatis配置
mybatis:
  config-location: classpath:mybatis.cfg
  mapper-locations: classpath:com/company/project/dao/**/*Mapper.xml
  type-aliases-package: com.company.project.dao
# MyBatis-Helper分页配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

#Redis配置
redis:
  node1:
    host: 114.67.102.8
    port: 6379
  node2:
    host: 114.67.102.8
    port: 6380