#
server:
  port: 7090
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-provider
  main:
    web-application-type: servlet

#########################
#（★）Eureka Client
#########################
eureka:
  #（1）实例配置
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #Eureka Client向Eureka Server发送心跳时间间隔
    lease-renewal-interval-in-seconds: 30
  #（2）客户端配置
  client:
    #CacheRefresh线程的调度频率
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://114.67.102.8:7010/eureka/