#
server:
  port: 7300
#
logging:
  config: classpath:logback-spring.xml
#
spring:
  application:
    name: study-springcloud-provider
  main:
    web-application-type: servlet
    banner-mode: 'off'
  profiles:
    active: eureka, @env@
#    active: nacos
