#
server:
  port: @server.port@
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-provider
  main:
    web-application-type: servlet
#########################
#（★）Eureka Client
#########################
eureka:
  #（▲）实例配置
  instance:
    #服务实例所在主机名
    hostname: study-springcloud-provider
    #服务实例的IP地址，默认null
    ip-address: 114.67.102.8
    #服务实例在注册中心的唯一实例id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #是否优先使用服务实例的IP地址，相较于hostname
    prefer-ip-address: true
    #向Server发送心跳间隔，默认30秒
    lease-renewal-interval-in-seconds: 30
    #指示Server在删除此实例之前收到最后一次心跳之后等待的时间，默认90秒
    lease-expiration-duration-in-seconds: 90
  #（▲）客户端配置
  client:
    #是否启用Client，默认true
    enabled: true
    #是否应将Client注册到Server以供其他服务发现，默认为false
    register-with-eureka: true
    #Client是否获取Server上的注册信息，默认为true
    fetch-registry: true
    #从Server获取注册表信息的频率，默认30秒
    registry-fetch-interval-seconds: 30
    #连接Server超时时间，默认5秒
    eureka-server-connect-timeout-seconds: 5
    #读取Server超时时间，默认8秒
    eureka-server-read-timeout-seconds: 8

    service-url:
      defaultZone: @eureka.client.defaultZone@


