#
server:
  port: 7200
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springcloud-provider
  main:
    web-application-type: servlet
#########################
#（★）Eureka Client
#########################
eureka:
  #（1）实例配置
  instance:
    hostname: study-springcloud-provider
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #Eureka Client向Eureka Server发送心跳时间间隔，默认30
    lease-renewal-interval-in-seconds: 30
  #（2）客户端配置
  client:
    register-with-eureka: true
    fetch-registry: true
    #CacheRefresh线程的调度频率，默认30
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: @eureka.client.defaultZone@
