version: '3.6'
services:
  study-springcloud-provider1:
    image: study/study-springcloud-provider:1
    restart: always
    ports:
      - 7201:7201
    environment:
      - SERVER_PORT=7201
      - EUREKA_SERVER_LIST=http://114.67.102.8:7101/eureka
    volumes:
      - /xdfapp:/xdfapp
  #    networks:
  #      - demo_net
  study-springcloud-provider2:
    image: study/study-springcloud-provider:1
    restart: always
    ports:
      - 7202:7202
    environment:
      - SERVER_PORT=7202
      - EUREKA_SERVER_LIST=http://114.67.102.8:7101/eureka
    volumes:
      - /xdfapp:/xdfapp
#    networks:
#      - demo_net
#  networks:
#  demo_net:
#    external: true