version: '3'
services:
  study-springcloud-provider1:
    image: study/study-springcloud-provider:1
    restart: always
    ports:
      - 7201:7200
    environment:
      - EUREKA_SERVER_LIST=http://eureka-server1:7101/eureka/,http://eureka-server1:7101/eureka/,http://eureka-server3:7103/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
  study-springcloud-provider2:
    image: study/study-springcloud-eureka:1
    restart: always
    ports:
      - 7202:7200
    environment:
      - EUREKA_SERVER_LIST=http://eureka-server1:7101/eureka/,http://eureka-server2:7102/eureka/,http://eureka-server3:7103/eureka/
    volumes:
      - /xdfapp:/xdfapp
    networks:
      - demo_net
  networks:
  demo_net:
    external: true